### ISSUE TITLE
Error showing Snackbar onDetectionTyped

### ISSUE THREAD

**Issue by antonygunawan94** [santa112358/detectable_text_field#14]
Hello,

I got an exception when trying to show snackbar onDetectionTyped

`W/IInputConnectionWrapper( 7059): endBatchEdit on inactive InputConnection

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Scrollable(axisDirection: down, physics: null, restorationId: "editable", dirty, dependencies: [_LocalizationsScope-[GlobalKey#f8757], UnmanagedRestorationScope, _InheritedTheme, ScrollConfiguration, MediaQuery, _EffectiveTickerMode], state: ScrollableState#7dfb1(position: ScrollPositionWithSingleContext#3cec7(offset: 0.0, range: 0.0..0.0, viewport: 19.0, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#deee0, ScrollDirection.idle), effective physics: ClampingScrollPhysics -> RangeMaintainingScrollPhysics)):
setState() or markNeedsBuild() called during build.

This ScaffoldMessenger widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: ScaffoldMessenger
    dependencies: [MediaQuery]
    state: ScaffoldMessengerState#449d8(tickers: tracking 1 ticker)
The widget which was currently being built when the offending call was made was: Scrollable
    axisDirection: down
`

Am I doing something wrong?

Thank you

**Comment by santa112358** [comment]
@antonygunawan94 
Thank you for the report. Fixed on latest version 2.0.1.
