### ISSUE TITLE
Error: TapUpDetails not match corresponding type TapDragUpDetails

### ISSUE THREAD

**Issue by jrpursuiteam** [santa112358/detectable_text_field#40]
Hi,

I am getting following error, appreciate help. 
Error (Xcode): ../../.pub-cache/hosted/pub.dev/detectable_text_field-2.0.4/lib/widgets/detectable_text_field.dart:88:35: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.

**Comment by rlee1990** [comment]
@jrpursuiteam I made a for that fixes the issue [here](https://github.com/rlee1990/detectable_text_field.git)
Will submit a pull request also.

**Comment by santa112358** [comment]
Fixed by #41
