### ISSUE TITLE
Can you display the chip widget inside the textfield?

### ISSUE THREAD

**Issue by Govindbetterlives** [santa112358/detectable_text_field#48]
Hi sir,
Can you help me how to show list and display chip input inside the textfield.
If you help me. you will save my life.

![256438502-656741ce-db9f-4a16-ba0a-425059bb821f](https://github.com/santa112358/detectable_text_field/assets/81243940/3a65d6e6-c63b-493b-8371-9a1fc9677e2c)

**Comment by NicoEssi** [comment]
Did you find the answer? @Govindbetterlives

**Comment by santa112358** [comment]
From version 3.0.0, I added DetectableTextEditingController.
You can use DetectableTextEditingController in conjunction with your custom widget to display a chip inside the text field.
