### ISSUE TITLE
Make DetectableText selectable

### ISSUE THREAD

**Issue by siuvoniazzi** [santa112358/detectable_text_field#7]
Currently it is not possible to let the user select text with the DetectableText Widget. This feature would be very welcome. Similar to SelectableText.

**Comment by santa112358** [comment]
Hi @siuvoniazzi , thank you for the request.
I recommend you to use SelectableText.rich and getDetectedTextSpan.
```dart
  SelectableText.rich(
    getDetectedTextSpan(
        decoratedStyle: style.copyWith(color: Colors.blue),
        basicStyle: style,
        source: "#hello world",
        detectionRegExp: hashTagRegExp),
  ),
```
If you have any questions, please reopen this issue. Thank you.
